In [2]:

import numpy as np
# creating a 2D array with shape (3, 4) and random values between -10 to 10
arr = np.random.randint(-10, 10, size=(3, 4))
print(f"Original Array:\n{arr}")


Original Array:
[[ -2  -7   8  -9]
 [ -9  -5  -6 -10]
 [  5  -4  -2  -3]]


In [3]:
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
print(np.__version__)

1.26.4


In [5]:
# using a tuple to create an array of objects

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [6]:
#  three dim array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [10]:

print("------------------------")

# 4D array with shape (2, 3, 4, 5)
four_dim_array = np.random.randint(0, 10, size=(2, 3, 4, 5), dtype=np.int32)

print("Shape of the 4D array:", four_dim_array.shape)
print("Number of dimensions:", four_dim_array.ndim)
print("\nThe 4D array:")
print(four_dim_array)


------------------------
Shape of the 4D array: (2, 3, 4, 5)
Number of dimensions: 4

The 4D array:
[[[[2 3 3 4 7]
   [1 6 5 5 5]
   [4 2 0 5 4]
   [2 2 0 9 3]]

  [[0 7 0 2 8]
   [4 8 2 6 8]
   [3 8 7 5 5]
   [9 3 8 7 7]]

  [[7 0 8 3 1]
   [9 2 5 7 2]
   [5 5 4 6 9]
   [6 3 1 8 1]]]


 [[[4 5 2 5 3]
   [6 9 9 8 7]
   [0 3 4 5 4]
   [7 4 7 1 1]]

  [[0 1 6 2 6]
   [2 5 3 9 9]
   [0 0 4 1 7]
   [4 5 8 8 3]]

  [[8 6 3 9 0]
   [6 8 9 3 3]
   [5 5 9 9 6]
   [5 4 0 8 1]]]]


In [13]:

arr = np.array([1, 2, 3, 4 , 5, 6, 7, 8], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4 5 6 7 8]]]]]
number of dimensions : 5
