In [10]:

import numpy as np
# creating a 2D array with shape (3, 4) and random values between -10 to 10
arr = np.random.randint(-10, 10, size=(3, 4))
print(f"Original Array:\n{arr}")


Original Array:
[[ -5   9  -2  -1]
 [ -5 -10  -4  -6]
 [  4   2  -6   4]]


In [11]:
print(type(arr))

<class 'numpy.ndarray'>


In [12]:
print(np.__version__)

1.26.4


In [13]:
# using a tuple to create an array of objects

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [14]:
#  three dim array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [15]:

print("------------------------")

# 4D array with shape (2, 3, 4, 5)
four_dim_array = np.random.randint(0, 10, size=(2, 3, 4, 5), dtype=np.int32)

print("Shape of the 4D array:", four_dim_array.shape)
print("Number of dimensions:", four_dim_array.ndim)
print("\nThe 4D array:")
print(four_dim_array)


------------------------
Shape of the 4D array: (2, 3, 4, 5)
Number of dimensions: 4

The 4D array:
[[[[2 1 2 0 4]
   [8 8 0 5 2]
   [6 0 2 3 3]
   [9 4 6 1 1]]

  [[5 6 5 5 3]
   [8 6 2 5 8]
   [1 9 4 1 9]
   [2 2 6 4 1]]

  [[5 3 5 8 6]
   [6 5 9 4 6]
   [4 9 9 4 8]
   [0 7 3 1 7]]]


 [[[6 9 7 3 7]
   [0 3 7 9 5]
   [4 6 0 8 1]
   [8 8 0 3 0]]

  [[4 1 0 1 0]
   [9 1 9 5 3]
   [1 6 6 5 5]
   [7 7 1 9 1]]

  [[7 5 2 0 5]
   [7 0 0 2 8]
   [3 0 5 9 3]
   [7 2 7 0 7]]]]


In [16]:

arr = np.array([1, 2, 3, 4 , 5, 6, 7, 8], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4 5 6 7 8]]]]]
number of dimensions : 5


In [19]:
# number list to array

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], ndmin = 5)

print(arr)
print('number of dimensions :', arr.ndim)
print(arr.shape)

[[[[[ 1  2  3  4  5  6  7  8  9 10]]]]]
number of dimensions : 5
(1, 1, 1, 1, 10)


In [20]:
# creating a 1D array
arr = np.array([1, 2, 3, 4, 5])

# setting the first element to 10
arr[0] = 10
print(arr)


[10  2  3  4  5]


In [21]:
# creating a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
# creating two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])


In [24]:
# adding the two arrays
print(arr1 + arr2)


[5 7 9]


In [25]:
# creating a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [26]:
# adding 1 to each element of the 2D array
print(arr_2d + 1)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [27]:
# creating a 1D array
arr1 = np.array([1, 2, 3])

# creating a scalar
arr2 = 10

# adding the scalar to the array
print(arr1 + arr2)


[11 12 13]


In [28]:
# creating a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# creating a 1D array
arr_1d = np.array([-1, 0, 1])

# adding the 1D array to the 2D array
print(arr_2d + arr_1d)

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


In [32]:
import numpy as np

# creating a 1D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# calculating the mean of the array
print(arr.mean())

# calculating the median of the array
print(arr.median())

# calculating the variance of the array
print(arr.var())

# calculating the standard deviation of the array
print(arr.std())

# calculating the maximum of the array
print(arr.max())

# calculating the minimum of the array
print(arr.min())

# calculating the sum of the array
print(arr.sum())

# creating a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# calculating the mean of the 2D array
print(arr_2d.mean())

# calculating the median of the 2D array
print(arr_2d.median())

# calculating the variance of the 2D array
print(arr_2d.var())

# calculating the standard deviation of the 2D array
print(arr_2d.std())

4.5


AttributeError: 'numpy.ndarray' object has no attribute 'median'