In [2]:

import numpy as np
# creating a 2D array with shape (3, 4) and random values between -10 to 10
arr = np.random.randint(-10, 10, size=(3, 4))
print(f"Original Array:\n{arr}")


Original Array:
[[ -2  -6  -4  -4]
 [  9   2   6   2]
 [  7   2 -10   8]]


In [3]:
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
print(np.__version__)

1.26.4


In [5]:
# using a tuple to create an array of objects

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [6]:
#  three dim array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [7]:

print("------------------------")

# 4D array with shape (2, 3, 4, 5)
four_dim_array = np.random.randint(0, 10, size=(2, 3, 4, 5), dtype=np.int32)

print("Shape of the 4D array:", four_dim_array.shape)
print("Number of dimensions:", four_dim_array.ndim)
print("\nThe 4D array:")
print(four_dim_array)


------------------------
Shape of the 4D array: (2, 3, 4, 5)
Number of dimensions: 4

The 4D array:
[[[[2 0 1 8 1]
   [0 1 1 9 0]
   [0 8 9 8 5]
   [6 3 4 1 0]]

  [[1 5 0 4 7]
   [0 4 2 3 8]
   [6 2 3 3 5]
   [8 8 1 7 6]]

  [[1 5 7 9 7]
   [7 1 1 5 3]
   [6 0 9 2 8]
   [6 2 6 4 3]]]


 [[[2 2 1 8 5]
   [0 9 3 8 7]
   [9 5 9 9 7]
   [1 8 1 9 6]]

  [[1 6 4 5 3]
   [5 1 5 6 4]
   [7 8 2 9 7]
   [9 1 0 9 4]]

  [[1 1 2 8 2]
   [9 5 4 3 7]
   [1 0 6 3 4]
   [7 9 6 9 1]]]]


In [8]:

arr = np.array([1, 2, 3, 4 , 5, 6, 7, 8], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4 5 6 7 8]]]]]
number of dimensions : 5


In [9]:
# number list to array

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(arr)
print('number of dimensions :', arr.ndim)
print(arr.shape)

[ 1  2  3  4  5  6  7  8  9 10]
number of dimensions : 1
(10,)
